---
dependency:
  name: galaxy
  requirements-file: collections.yml
driver:
  name: docker
platforms:
  - name: instance_latest
    image: openwrtorg/rootfs:latest
    pre_build_image: false
    groups:
      - openwrt
    environment:
      openwrt_image_tag: latest
  - name: instance_x86-64-18.06.6
    image: openwrtorg/rootfs:x86-64-18.06.6
    pre_build_image: false
    groups:
      - openwrt
    environment:
      openwrt_image_tag: x86-64-18.06.6
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
